# Generated by Django 6.0.2 on 2026-02-24 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('original_filename', models.CharField(max_length=512)),
                ('file_size', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting'), ('enriching', 'Enriching'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TikaMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.CharField(blank=True, default='', max_length=50)),
                ('author', models.CharField(blank=True, default='', max_length=512)),
                ('title', models.CharField(blank=True, default='', max_length=1024)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('full_text', models.TextField(blank=True, default='')),
                ('raw_metadata', models.JSONField(default=dict)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tika_metadata', to='tiki.uploadedfile')),
            ],
        ),
        migrations.CreateModel(
            name='DCATOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonld', models.JSONField(default=dict)),
                ('empty_fields', models.JSONField(default=list)),
                ('user_edits', models.JSONField(default=dict)),
                ('is_finalized', models.BooleanField(default=False)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dcat_output', to='tiki.uploadedfile')),
            ],
        ),
        migrations.CreateModel(
            name='ClaudeEnrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_themes', models.JSONField(default=list)),
                ('generated_description', models.TextField(blank=True, default='')),
                ('suggested_keywords', models.JSONField(default=list)),
                ('prompt_used', models.TextField(blank=True, default='')),
                ('raw_response', models.JSONField(default=dict)),
                ('model_used', models.CharField(blank=True, default='', max_length=100)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claude_enrichment', to='tiki.uploadedfile')),
            ],
        ),
    ]
